name: Dot Dash
favicon: null
layout_spectrum: 0.5767763026524335
typography_spectrum: 0.275511191226542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3254737099632621
  lightness: 0.38960249931551516
  saturation: 0.021348376758396626
  rhythmicContrast: 0.18321176362223923
purpose: []
